# Generated by Django 3.2.5 on 2021-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_tests', '0001_create_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoicequestion',
            unique_together={('number', 'questionnaire'), ('text', 'questionnaire')},
        ),
    ]
