# Generated by Django 3.2.5 on 2021-07-29 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med_tests', '0002_change_multiple_choice_question_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
