# Generated by Django 3.2.5 on 2021-08-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_tests', '0003_add_timestamp_to_questionnaire_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
