# Generated by Django 3.2.5 on 2021-08-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_tests', '0004_add_default_for_qr_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='response_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_tests.responseoption'),
        ),
    ]
