# Generated by Django 3.2.5 on 2021-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_tests', '0007_add_qr_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
