# Generated by Django 3.2.5 on 2021-08-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('med_tests', '0008_add_patronymic_to_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='response_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='med_tests.responseoption'),
            preserve_default=False,
        ),
    ]
