# Generated by Django 3.2.5 on 2021-09-06 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med_tests', '0009_edit_qr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
