# Generated by Django 3.2.5 on 2021-11-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med_tests', '0010_timestamp_to_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_tests.questionnaire')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_tests.questionnaireresponse')),
            ],
        ),
    ]
